# Generated by Django 4.1.2 on 2022-10-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TableMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("overview", models.TextField()),
                ("genre", models.CharField(max_length=200)),
                ("rating", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Movie",
            },
        ),
    ]
