# Generated by Django 4.1.4 on 2022-12-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_coming_film_top_film_trending_film"),
    ]

    operations = [
        migrations.AddField(
            model_name="coming_film",
            name="idcom",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="top_film",
            name="idtop",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trending_film",
            name="idtren",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
