# Generated by Django 4.1.4 on 2022-12-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_coming_film_idcom_top_film_idtop_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="searching_film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idcom", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(max_length=225)),
                ("overview", models.TextField()),
                ("adult", models.CharField(max_length=225)),
                ("languages", models.CharField(max_length=200)),
                ("release", models.CharField(max_length=200)),
                ("poster", models.CharField(max_length=200)),
                ("vote", models.CharField(max_length=200)),
            ],
        ),
    ]
